# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
lasso_regression <- function(gram_matrix, xy, lambda, penalty_factors, max_iter = 1000L, tolerance = 1e-6) {
    .Call(`_PVAR_FiNNO_lasso_regression`, gram_matrix, xy, lambda, penalty_factors, max_iter, tolerance)
}

